[options]
admin_passwd = admin123

# Database config
db_host = localhost
db_port = 5432
db_user = odoo
db_password = 123456

# Addons path
addons_path = /Users/a1/odoo-dev/odoo17/addons,/Users/a1/odoo-dev/custom-addons/OCTA

